### ISSUE TITLE
Cannot install via Anaconda

### ISSUE THREAD

**Issue by NicholasDeLateur** [cytoflow/cytoflow#235]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
I got the following error message when clicking "Install" via the Anaconda Navigator, following the instruction as per https://cytoflow.readthedocs.io/en/1.0/INSTALL.html#install

PackagesNotFoundError: The following packages are not available from current channels:

- cytoflow==1.0
- envisage==4.7.0
- cytoflow==1.0
- libpng[version='>=1.6.35, - cytoflow==1.0
- matplotlib==3.0.2
- cytoflow==1.0
- numpy==1.15.4
- cytoflow==1.0
- openssl[version='>=1.1.1a, - cytoflow==1.0
- pyface==6.0.0
- cytoflow==1.0
- pyopengl==3.1.1a1
- cytoflow==1.0
- python==3.6.7
- cytoflow==1.0
- python-dateutil==2.7.5
- cytoflow==1.0
- qt[version='5.9.7,>=5.9.7, - cytoflow==1.0
- scikit-learn==0.20.1
- cytoflow==1.0
- sqlite[version='>=3.26.0, - cytoflow==1.0
- traits==4.6.0
- cytoflow==1.0
- traitsui==6.0.0

Current channels:

- https://conda.anaconda.org/bpteague/win-64
- https://conda.anaconda.org/bpteague/noarch
- https://conda.anaconda.org/default/win-64
- https://conda.anaconda.org/default/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org

and use the search bar at the top of the page.

**Comment by NicholasDeLateur** [comment]
Working on a fresh install of Anaconda3 5.2.0 64bit (which is most official Python 3.6 version according to https://docs.anaconda.com/anaconda/user-guide/faq/#anaconda-faq-35) I reproduced the problem (wasn't 100% what version on Anaconda I was on before)

**Comment by bpteague** [comment]
Instructions have been updated! If you're still having trouble, please re-open.
