### ISSUE TITLE
Set linear threshold on symlog

### ISSUE THREAD

**Issue by NicholasDeLateur** [cytoflow/cytoflow#240]
[Enhancement] 

Whenever a symlog axis scale is allowable, give the user the option for where the linthreshx or linthreshy as applicable is.

**Comment by bpteague** [comment]
Do you mean the "logicle" axis scale? And there's no way I can expose that much detail in the GUI, and I'm not sure how I'd implement that in the modules.... marking WONTFIX for now, re-open if this is something you're desperate for.
