### ISSUE TITLE
Samples not loading propperly

### ISSUE THREAD

**Issue by pauloxisto** [cytoflow/cytoflow#242]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? 
I was trying to load my tubes acquired at BD Accuri
  - What happened?
The tubes didnt load as expected, mentioning that my tubes did not have data.
  - What did you expect to happen?
 Well, the tubes were supposed to load haha
**Don't forget to attach the log file to this bug report!** 

<img width="1080" alt="Untitled" src="https://user-images.githubusercontent.com/50554953/57586518-600b9400-74cd-11e9-8f47-6a1849694084.png">
[buglog.log](https://github.com/bpteague/cytoflow/files/3170433/buglog.log)

I could not attach my .FCS file here, but when I try to send an e-mail it also shows me a bug and stops me from sending it.

**Comment by mshyu24** [comment]
I have also had this issue with files gathered from a BD Accuri

**Comment by bpteague** [comment]
I'm sorry that this has been left to languish. Could someone please attach an FCS file that shows the bug?

**Comment by pauloxisto** [comment]
> I'm sorry that this has been left to languish. Could someone please attach an FCS file that shows the bug?

No worries! Fortunately my e-mail notified me about your inquiry and I could upload an Accuri-derived FCS file for you.
[B01 CHO-K1.zip](https://github.com/cytoflow/cytoflow/files/7884196/B01.CHO-K1.zip)
.

**Comment by bpteague** [comment]
Thanks. I can reproduce the bug. Should have a fix soon.

**Comment by bpteague** [comment]
Fixed! Those Accuri C6 files are strange -- this is not the first one I've had trouble with. I'll have a new release out this afternoon -- if it's still an issue, please re-open this bug.
