### ISSUE TITLE
Erro in inporting data from BD accuri

### ISSUE THREAD

**Issue by benzonbenjamin** [cytoflow/cytoflow#247]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? import fcs file
  - What happened? uneexpected error
[error importing.log](https://github.com/bpteague/cytoflow/files/3638949/error.importing.log)

  - What did you expect to happen?to import file
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Ugh -- there are too many non-conformant FCS files out there. I can't debug this unless you attach the file that's giving you trouble.  

Also, this looks like a quite old version of `cytoflow` -- please try both the most recent version, as well as the one I'll be publishing here in the next couple of weeks.  If it's still broken, (a) re-open the bug, and (b) attach the problematic file to the bug report.
