### ISSUE TITLE
Exporting plots in cytoflow commandline

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#253]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac, jupyter
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
10.14.6
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:
  - What were you trying to do?
Save flow plots to png, eps, jpg etc.
  - What happened?
Not able to do this? I can't find anything in the docs.
  - What did you expect to happen?
I was hoping to be able to dump a series of flow histogram plots to a folder in various formats in high-resolution.
  
**Don't forget to attach the log file to this bug report!**

**Comment by kristjaneerik** [comment]
You could do:
```python
# ... code for plotting your View
fig = plt.gcf()
fig.savefig("myfile.png", dpi=300)
```

If you're using this in a Jupyter notebook, make sure you are running those two lines in the same cell as the code you're generating the view / plots in, otherwise you get an empty image.

**Comment by bpteague** [comment]
`cytoflow` uses the `matplotlib.pyplot` stateful interface for making
plots.  Thus, there are two ways to save the plots.  The first is to use the
`matplotlib.pyplot.savefig` -- see the `matplotlib` documentation
for more details.  (This option gives you the greatest flexibility in format,
resolution, etc.)

If you are using the Jupyter notebook, the second is to replace the
`%matplotlib inline` magic with `%matplotlib notebook`.  Then,
when you make a plot, the plot remains interactive.  
Click the "disk" icon to download a copy of the image.

(I've added this to the documentation)
