### ISSUE TITLE
Plot label handling in barplot horizontal orientation

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#254]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac, jupyter
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
10.14.6
### SEVERITY (Critical? Major? Minor? Enhancement?):
Minor
### DESCRIPTION:
  - What were you trying to do?
Orient barplots to horizontal orientation with .plot(...,orientation="horizontal")
  - What happened?
Axes were properly re-oriented but not the main x and y labels. Tick labels seem to be correctly re-oriented.
  - What did you expect to happen?
I was expecting the labels to flip during horizontal orientation.
  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Fixed in ba87579aef09bf8e02e27fb9a27c103654027892
