### ISSUE TITLE
Sort plot labels with natural sorting

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#256]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac, jupyter
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
10.14.6
### SEVERITY (Critical? Major? Minor? Enhancement?):
Minor enhancement
### DESCRIPTION:
  - What were you trying to do?
Plot flow histograms.
  - What happened?
Plots sorted in non-natural sorting order.
  - What did you expect to happen?
I was hoping plots would handle labels with natural sorting a la (https://pypi.org/project/natsort/)
  
**Don't forget to attach the log file to this bug report!**

**Comment by bhwein** [comment]
This seems to be the case in HistogramView. BarChartView seem to plot in order specified from tube setup.

**Comment by bpteague** [comment]
@kristjaneerik fixed this! Thanks, Eerik!
