### ISSUE TITLE
Progress bar support during import_op

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#257]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac, jupyter
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
10.14.6
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:
  - What were you trying to do?
Load many tubes during import_op.
  - What happened?
Takes a while..
  - What did you expect to happen?
  Progress monitoring.

Importing many tubes can take a long time and it would be nice to monitor progress in jupyter notebook. I hacked the code a little to incorporate this using notebook from tqdm package. 

In cytoflow.operations.import_op.apply():

![image](https://user-images.githubusercontent.com/28678480/76340337-cde14180-62d1-11ea-8fd2-63c2fb63816a.png)
![image](https://user-images.githubusercontent.com/28678480/76340002-3e3b9300-62d1-11ea-83bd-41a3748f14dd.png)

**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
That's cool! Importing isn't the only thing that can take a while, and it would be nice to have more feedback for long-running operations.  I've broadened the idea and opened a new tracking bug in #317 . Closing this one.
