### ISSUE TITLE
Homebrew cask

### ISSUE THREAD

**Issue by heesters** [cytoflow/cytoflow#260]
More a feature request...
Great initiative! Flowjo's monopoly is hurting academics.
Is it possible to add this to homebrew cask (osx)?
That would make updating easy.
Thanks!

**Comment by bpteague** [comment]
Oh man. I don't use a Mac on a regular basis, so I actually don't know much about cask. I don't think updating is a huge deal -- the point-and-click package is "just" a plain Mac app, and if you're using the Python modules, `conda update` is pretty easy too (:  I don't relish the idea of supporting one more distribution method.

I'm going to mark this WONTFIX for now, but if you've got a "good reason" -- or want to volunteer to set it up and maintain it (: -- please feel free to comment.
