### ISSUE TITLE
FSC v SSC plotting issue

### ISSUE THREAD

**Issue by delrosni** [cytoflow/cytoflow#266]
I'm running into a pretty bizarre issue when I plot the FSC vs SSC in cytoflow. The large values almost seem to "wrap around" the axes. 

linear axes:
![LineraFSCvSSC](https://user-images.githubusercontent.com/8440743/88601402-71cf4d80-d025-11ea-95c9-ef2a999c15ca.png)

```
set_default_scale("linear")
ScatterplotView(xchannel = "FSC 488/10-A",
                     ychannel = "SSC 488/10-A").plot(ex_0, alpha = 0.05)
plt.savefig('LineraFSCvSSC.png', dpi=100)
```

converting to log is also confusing:
![LogFSCvSSC](https://user-images.githubusercontent.com/8440743/88601463-9b887480-d025-11ea-8f71-a7e18f4d700a.png)

I never saw this issue when working with Cytoflex's exported FCS 3.0 files. I started seeing this issue working with ZE5's 3.1 FCS files. A few more details:

### DESCRIPTION:
  - What were you trying to do? create a viable cells gate using FSC-A, SSC-A channels
  - What happened? values don't seem correct when plotted...larger values seem to artifactually wrap around the x,y axes

**Comment by kristjaneerik** [comment]
https://github.com/bpteague/cytoflow/blob/master/cytoflow/operations/import_op.py#L422-L435 this section is the culprit.

The ZE5 has `range_bits == 30` and `data_bits == $PnB == 32` in this case.

We also have that `$PnR = 2147483647 = 2**31 - 1` and `$DATATYPE = I`.

`range_bits` should actually be 31 in this case; when I set `range_bits = 31`, the data load as expected.

Perhaps
```python
range_bits = int(math.log(data_range, 2))
```
should instead be
```python
range_bits = int(math.ceil(math.log(data_range, 2)))
```
which would fix the issue for the ZE5.

@bpteague would this change break processing of files that initially necessitated the bit shifting in the first place?

**Comment by bpteague** [comment]
Ugh, WHY is there so much diversity in FCS files?? Yes, that could cause what you're seeing.  I think that change is probably fine -- though I'd love to add it to the files that I use to stress-test the importer! Would one of you mind attaching an example file? I'm going to go ahead and make @kristjaneerik 's suggested change, will roll out in the next release, in a few weeks.
