### ISSUE TITLE
Flow Cytometry

### ISSUE THREAD

**Issue by zl6y19** [cytoflow/cytoflow#273]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  I want to set up an experiment and its successed. However, when I click on "Import!" button, the "Import Data" shows the ❌ rather than ✅.
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
After the error occurs, please click the "Report a bug" button. This will cause `cytoflow` to create a log file, which you can then attach to this bug. That information will help me track this down. I'm closing the issue for now -- please re-open when you've got the log attached.
