### ISSUE TITLE
Error prevents creation of a new experiment

### ISSUE THREAD

**Issue by mpiersonsmela** [cytoflow/cytoflow#278]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):

Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):

OSX 10.14 (Mojave)

### SEVERITY (Critical? Major? Minor? Enhancement?):

Major

### DESCRIPTION:
  - What were you trying to do?

Create a new experiment

  - What happened?

Got an exception:

```
An exception has occurred.  Please report a problem from the Help menu!

Afterwards, may need to restart Cytoflow to continue working.

Error: IndexError: list index out of range

Location:   File "cytoflowgui/workflow.py", line 283, in recv_main
Thread: local workflow recv
```

  - What did you expect to happen?
  
No error.

**Don't forget to attach the log file to this bug report!**

**Comment by mpiersonsmela** [comment]
[error.log](https://github.com/bpteague/cytoflow/files/5380243/error.log)

**Comment by bpteague** [comment]
Thanks for the report (and sorry for not responding sooner -- I teach at a small college and it's been a crazy year, for obvious reasons.)

I'll be releasing a new version in the next few weeks, and I'm pretty sure this is fixed. If not, please do not hesitate to re-open the bug.
