### ISSUE TITLE
Are figure/axis handles returned by plot() methods?

### ISSUE THREAD

**Issue by icheo2l5** [cytoflow/cytoflow#279]
### PLATFORM (Mac, PC, Linux, other):
Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
OSX 10.15

### SEVERITY (Critical? Major? Minor? Enhancement?):
Minor

### DESCRIPTION:
  - What were you trying to do?
Wanted to modify some plots generated by `view` methods after the plots are created.

  - What happened?
Couldn't figure out how to access the matplotlib.pyplot figures or axes.

  - What did you expect to happen?
Allow the handles to be returned so users can further configure the plots.
  

I looked into the `plot()` method of `cytoflow.views.base_views.BaseView` and it seems that the figure object isn't retured by the method. Is there a reason for this? Just curious.

Alternatively, I could use other libraries to plot all the data that are readily accessible by the underlying pandas dataframe, but it would be much nicer to be able to modify the plots generated by this very useful flow cytometry package!

**Comment by icheo2l5** [comment]
Oops! Just found another workaround from another issue #253 :

Use `matplotlib.pyplot.gcf()` to access the figure after the plots are created.

**Comment by bpteague** [comment]
Yep, I'd use `matplotlib.pyplot.gcf()` to get the `Figure` that was just generated. `cytoflow` relies pretty heavily on `seaborn`, which in turn uses the (stateful) `pyplot` interface to `matplotlib`. That's why I'm not returning the axes or figure, for example.
