### ISSUE TITLE
Fail to load .csv file with cytometry data

### ISSUE THREAD

**Issue by ejaabr** [cytoflow/cytoflow#282]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? I was trying to load a csv file with cytometry data
  - What happened? An error dialog appear.
The following msg appear on terminal
2020-12-09 13:01:51,761 ERROR:root:Error: TypeError: expected str, bytes or os.PathLike object, not numpy.int64

Location:   File "/home/eaguilar/bin/anaconda3/envs/cytoflow/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
Thread: MainThread

  - What did you expect to happen?
to load the file content without any issues
  
**Don't forget to attach the log file to this bug report!** 
[2020-12-09.log](https://github.com/bpteague/cytoflow/files/5667161/2020-12-09.log)

**Comment by bpteague** [comment]
The "import" function was really poorly documented in the last release. I'm sorry! I suspect that your CSV file was improperly formatted -- if so, the error message you received wasn't terribly useful.

I've improved the documentation, at least.  Head over to https://github.com/cytoflow/cytoflow/blob/docs/docs/user_manual/howto/import.rst and see if your CSV file matches the format that `cytoflow` expects. I'll leave this bug open until I improve the error message.

**Comment by bpteague** [comment]
And now there's a better error message -- it will appear in the next version, which should be released in the next few weeks.

**Comment by ejaabr** [comment]
Thanks!

[]sEduardo "Education is an admirable thing, but it is well to remember from time to time that nothing that is worth knowing can be taught." Oscar Wilde 

    On Wednesday, July 28, 2021, 11:29:07 AM GMT-3, Brian Teague ***@***.***> wrote:  
 
 


And now there's a better error message -- it will appear in the next version, which should be released in the next few weeks.
