### ISSUE TITLE
Can't save workflow

### ISSUE THREAD

**Issue by nstone8** [cytoflow/cytoflow#283]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
PC

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Windows 10 Home build 19042.685
### SEVERITY (Critical? Major? Minor? Enhancement?):
Critical
### DESCRIPTION:
  - What were you trying to do?
  Save a workflow
  - What happened?
  An unhandled exception occurred
  - What did you expect to happen?
  My workflow to be saved
  
**Don't forget to attach the log file to this bug report!** 
[crash.log](https://github.com/bpteague/cytoflow/files/5712664/crash.log)

**Comment by bpteague** [comment]
Yikes! Thanks for the bug report. I'm pretty sure this has been fixed; I'll be releasing a new version in the next couple of weeks. Try that and let me know if the bug persists; if so, please re-open.

**Comment by nstone8** [comment]
Awesome, thanks for looking into this!
