### ISSUE TITLE
getting more control over logicle-scale histograms

### ISSUE THREAD

**Issue by kmattioli** [cytoflow/cytoflow#310]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do? --> Trying to get more control over the histograms; mainly just want to change their colors and some other aesthetics. (Doesn't seem like passing an array of colors to `HistogramView.plot(**{"color": [x, y]})` works to change the default colors when using `huefacet`? If there's a way to do that, that would also work...)
  - What happened? --> After following the advice in #297 I got the logicle scale to work on a new figure but the histogram looks skewed (bins are bigger towards smaller x values) after calling `sns.distplot()` followed by setting the scale; see code and plot below.
  - What did you expect to happen? --> What am I missing to generate a normal-looking histogram as output by HistogramView.plot()?
  
An example:
```
import cytoflow.utility.logicle_scale
import cytoflow.utility as util

# generate the scales for matplotlib
logicle_x = util.scale_factory('logicle', ex, channel='RedFL1')

fig = plt.figure(figsize=(3, 2))
ax = sns.distplot(tmp["RedFL1"], kde=False)

# set logicle scale
ax.set_xscale('logicle', **logicle_x.get_mpl_params(ax.xaxis))
```

![image](https://user-images.githubusercontent.com/19721242/116606603-f9bced80-a8fe-11eb-8954-795ea0162684.png)

**Comment by bpteague** [comment]
Let me come back to the logicle issue in a minute. It looks like the underlying issue you (and @crife-pact in #297) are trying to solve is that you'd like to use some different colors. Fair enough! In a2828a9ac611ba501755879c51c4e45ed94e4d19 I added a `palette` argument to `plot()`, which will let you choose different colors. (This functionality was added to `seaborn` after I initially wrote this function, or it would have been there earlier.)

**Comment by bpteague** [comment]
As for why your histogram looks weird -- to be honest, the logicle scale really isn't intended to be used outside of the rest of the `cytoflow` ecosystem. In this case, what's happening is that, as part of making a histogram, `seaborn` is finding some "optimal" set of bins, then binning the data to compute the height of each bar in the histogram. It's doing so on the "raw" data -- the bins it computes are equally-spaced in linear space, but of course they won't be equally-spaced in "logicle" space. Then you're plotting a histogram and applying the logicle transform to the axis -- and now the bins aren't equally-spaced. Hence the screwy output.

If you really want to take this approach, what you need to do is:
- Create the logicle scale
- Apply the scale to the data
- Use the scaled data to compute the bins you want (using `numpy.linspace` or similar)
- Apply the inverse scale to the bins
- Plot the (raw) data with the bins you computed
- Apply the logicle scale to the axis

Of course, `cytoflow.HistogramView` does all this for you (;
