### ISSUE TITLE
CytoflowError has no attribute "value"

### ISSUE THREAD

**Issue by pintomollo** [cytoflow/cytoflow#315]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Linux

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Ubuntu 20.04.2 LTS; on Miniconda3 Python3.8 (also happened with the point&click binary and the pip version)

### SEVERITY (Critical? Major? Minor? Enhancement?):
Major

### DESCRIPTION:
  - What were you trying to do?
 Load tube
  - What happened?
 An error is raised "CytoflowError has no attribute "value""
  - What did you expect to happen?
 Raise the proper error.

There seems to be a mistake in cytoflowgui/import_dialog.py l.719:

The proper raise should be :
                raise RuntimeError("FCS reader threw an error on tube {0}: {1}"\
                                   .format(path, str(e)))

Instead of the current:
                raise RuntimeError("FCS reader threw an error on tube {0}: {1}"\
                                   .format(path, e.value))

  
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
@pintomollo Thanks! Good catch -- fixed in ea71ee5b13f78018040ee1b08325991a70297404
