### ISSUE TITLE
Loss of saved workflow: after an error in the GUI, clicking "save" reduces the existing .flow file to 0kb 

### ISSUE THREAD

**Issue by cbinny** [cytoflow/cytoflow#318]
[20210909.log](https://github.com/cytoflow/cytoflow/files/7136489/20210909.log)
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do?

Save a .flow file in which I'd previously done something that generates a warning in the GUI. In this case (attached logfile), I'd tried to make a "Channel Statistic" table in which I'd told the drop-downs to use the same facet in both the "Rows" and "Subrows", correctly generating the warning "Can't reuse facets". Then next time I click "Save", I get an error message from cytoflow and the .flow file is wiped out.

This is a routine problem for me. I think it only happens as a result of my doing something the programme doesn't expect (e.g. clicking outside the graph when drawing a polygon gate on a scatter plot), but it has happened at many (all?) stages of using the software, from importing the sample data onwards.

  - What happened?
Upon clicking "Save", I'm shown an error message by Cytoflow and the .flow file I currently have open is reduced to 0kb. I can dismiss the error message and keep working, but subsequent attempts to save do nothing; no error messages, but the 0kb save file never changes. If I close cytoflow and try to open that 0kb .flow file it fails, and cytoflow asks if I'm sure it's a cytoflow file.

NB: This still happens with known-good .flow files. E.g. I successfully save a .flow file, re-open it on a different day to look again at the data, then this error occurs and wipes that old .flow file down to 0kb.

  - What did you expect to happen?
Clicking "Save" allows me to save the workflow as normal, or at least doesn't delete the workflow data that I've saved previously. 

**Don't forget to attach the log file to this bug report!** 

NB: I love this software, thanks for the ongoing work! But knowing that making a simple error will wipe out all my work so far -- including work that I have already successfully saved! -- makes it a pretty stressful experience ;).

**Comment by bpteague** [comment]
Hi @cbinny  - yeah, that's a pretty critical error. You weren't the only person it was affecting. I think I've got it fixed, and will have it in the next release -- here in the next week. If you are still experiencing this with the new version, please re-open this bug? And if you could attach a "known good" file that gets wiped out when you save it, and preferably a log file as well, that would be great.

And I'm glad you're finding the software useful, despite the remaining bugs!
