### ISSUE TITLE
huepalette as attribute or kwarg

### ISSUE THREAD

**Issue by maaikesangster** [cytoflow/cytoflow#321]
### PLATFORM (Mac, PC, Linux, other):
Linux

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Ubuntu

### SEVERITY (Critical? Major? Minor? Enhancement?):
Minor enhancement

### DESCRIPTION:
  - What were you trying to do?
  - 
 I was trying to specify the colors of my huefacets, instead of having the default colors.

  - What happened?

I edited the code to add huepalette as an attribute to the BaseView object (just like xfacet, yfacet, huefacet and huescale) which works well. I wanted to submit a pull request for this change, but then I saw that you recently already added huepalette as a kwarg to the plot function. First of all, thanks for that, I think it's very useful addition! Personally, however, I think it might be more intuitive the way I did it, because huefacet is also added as an attribute, so you would specify the facet and the palette in the same place in the code. Maybe there's a good reason for not doing that do, and if so I would be curious to know it. Thanks!

**Comment by bpteague** [comment]
Hi @maaikesangster - I'm so glad to know that me and @kristjaneerik aren't the only people using the module API (: And "I wanted to submit a pull request" makes me very happy indeed, even if there's not actually a PR that resulted (:

The reason things are split up this way is pretty basic. The attributes of the `IView` objects -- `xfacet`, `yfacet`, etc -- control *what* is plotted. The keyword args to `plot` control *how* it is plotted. That is to say, the attributes affect which data is passed into the underlying plotting routines. The keyword args are mostly just passed along unchanged, to modify the visual style.

Please keep submitting bugs and suggestions. I teach at a regional college, so the time I have to work on `cytoflow` may be a little sporadic, but I'm still around and working on it.

**Comment by maaikesangster** [comment]
That makes sense, thank you!
