### ISSUE TITLE
Error saving file, final file has 0 KB

### ISSUE THREAD

**Issue by catalantat** [cytoflow/cytoflow#324]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
PC

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Windows 10
### SEVERITY (Critical? Major? Minor? Enhancement?):

Save can not be performed
### DESCRIPTION:
  - What were you trying to do?
Save file
  - What happened?
Error pop-up
  - What did you expect to happen?
Successfully save the file
  [error.log](https://github.com/cytoflow/cytoflow/files/7353818/error.log)
**Don't forget to attach the log file to this bug report!**

**Comment by bpteague** [comment]
Thanks for the bug report. This was fixed in commit 51a559547367ec6cebb553e51a3bb8f329b8ac1c and will be released some time in the next week!
