### ISSUE TITLE
Add single datapoints to barplots

### ISSUE THREAD

**Issue by alefrol638** [cytoflow/cytoflow#343]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
All
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
All
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:

When plotting statistics in a barplot, it would be nice to have single datapoints in the barplots in addition to error bars. (see attachment)
<img width="798" alt="Screenshot 2022-09-13 at 21 28 16" src="https://user-images.githubusercontent.com/85966334/189993486-c2f02ade-6154-47de-b773-27532f8b7674.png">

**Comment by bpteague** [comment]
Thanks for the suggestion, but this isn't going to happen. Cytoflow is not, and never will be, a general-purpose statistics plotting package. If you don't like its plots, export the statistic in a CSV file and open in your favorite plot-making package.
