### ISSUE TITLE
Files from a Guava EasyCyte HT causing exceptions

### ISSUE THREAD

**Issue by germo006** [cytoflow/cytoflow#345]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - I've been trying to import data from a Guava EasyCyte HT. 
  - I can export only "analyzed groups"
  -- These can be FCS 3.0, FCS 2.0, or `.csv`
  - The FCS 3.0 standard, I assume, is the best here. Cytoflow does not read this properly, seeing only the first well in the file. There should be 24, as the Guava software exports a 64 Mb file containing all the data from the run. The program can plot and play with that data, but only the very first well in the dataset. (B03 in the actual 96-well plate)
  - The FCS 2.0 standard exports each well analyzed as a separate `.fcs` file, which is more in line with what the docs imply I need. However, if I try to "add tubes" with any of these files, there's an error and I have to restart the program. The result is the same whether I try to use 1 or 24 files. 
  - `.csv` option makes nice files with a row for each event detected, but they can't interact with Cytoflow.
  
**Don't forget to attach the log file to this bug report!** 
[NPG_3Nov2020.log](https://github.com/cytoflow/cytoflow/files/9932550/NPG_3Nov2020.log)

**If you are having trouble with a particular FCS file, please attach that file too.**
even zipped, the FCS 3.0 file is too large to upload to GitHub

**Comment by bpteague** [comment]
I need a file to reproduce this. I readily admit that the Cytoflow doesn't handle multiple-data-set FCS files particularly well. The FCS 2.0 route, with one file per well, is the easiest way to go, but SO many vendors don't implement the FCS spec particularly well. In this case, it looks like Cytoflow is getting a piece of metadata in a format that it doesn't expect, but without a test file I can't troubleshoot it. Please upload a test file for me to try out, either here or somewhere else.
