### ISSUE TITLE
Serializing experiment objects

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#348]
### Thank you for your bug report!  

Please fill out the following template.

### PLATFORM (Mac, PC, Linux, other):
Mac
### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
OS 12.5
### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement
### DESCRIPTION:
  - What were you trying to do?
  - What happened?
  - What did you expect to happen?
I was wondering if there was a good way to serialize Experiment objects so that can be saved and re-opened later on (to avoid the slow import process). I have been trying to pickle them. Although I seemingly re-open them, something seems to happen after I `apply()` gaussian or threshold operations to them. I get an error that channels can't be found anymore even though I can see them before the operation using `Experiment.channels`.

**Don't forget to attach the log file to this bug report!** 

**If you are having trouble with a particular FCS file, please attach that file too.**

**Comment by benweinberg89** [comment]
This is what appears in the channels variable after trying to apply a 2d gaussian filter:
'Traceback (most recent call last):\n  File "/Users/benweinberg/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py", line 189, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "/Users/benweinberg/opt/anaconda3/envs/cf/lib/python3.8/site-packages/cytoflow/experiment.py", line 197, in _get_channels\n    return sorted([x for x in self.data if self.metadata[x][\'type\'] == "channel"])\n  File "/Users/benweinberg/opt/anaconda3/envs/cf/lib/python3.8/site-packages/cytoflow/experiment.py", line 197, in <listcomp>\n    return sorted([x for x in self.data if self.metadata[x][\'type\'] == "channel"])\nKeyError: \'FSC-A\'\n'

**Comment by CaRniFeXeR** [comment]
Can you maybe provide a jupyter notebook showing this problem?

**Comment by benweinberg89** [comment]
@CaRniFeXeR It will take me some time to do that. Perhaps I will try serializing some of the kiani data. Serializing could help address Issue #349.

**Comment by bpteague** [comment]
While I admit that I had never before attempted to pickle and unpickle an Experiment, it seems to work fine for me. If you can reproduce this in the new release, please re-open and include a minimal reproducible example.
