### ISSUE TITLE
Is there a way to save a Python cytoflow experiment as a .flow file to load into the GUI version of cytoflow?

### ISSUE THREAD

**Issue by andrenguyen** [cytoflow/cytoflow#349]
### PLATFORM (Mac, PC, Linux, other):

Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):

OSX 11.7.2

### SEVERITY (Critical? Major? Minor? Enhancement?):

Question or enhancement?

### DESCRIPTION:

Is there a way to save a Python cytoflow experiment as a .flow file to load into the GUI version of cytoflow? Thanks!

**Comment by bpteague** [comment]
No, because you can do things with a Python script that you can't do in the GUI. Sorry!
