### ISSUE TITLE
PCA Cumulative Proportion

### ISSUE THREAD

**Issue by aliceberd** [cytoflow/cytoflow#355]
### PLATFORM (Mac, PC, Linux, other):
PC

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):
Windows 11

### SEVERITY (Critical? Major? Minor? Enhancement?):
Enhancement

### DESCRIPTION:
  - What were you trying to do?
I've been using the software, and my main objective is to publish the results I've obtained in a scientific journal.
However, I've been asked to improve the interpretability of results by incorporating the cumulative proportion explained by the principal components in my statistical PCA (Principal Component Analysis) analyses.
So I'm seeking assistance on how to extract these cumulative proportion values from the PCA analyses and add them to the resulting graphs.

Thank you very much!

Examples below:
![Biplot_of_the_variables_dcf3eea254](https://github.com/cytoflow/cytoflow/assets/61164169/150fb542-e03b-40f3-91bb-9fcdf843eb73)
![r_pca_summary_62029f378f](https://github.com/cytoflow/cytoflow/assets/61164169/f4cedcf1-d0d4-44a7-9c9a-24f9633592b2)

**Comment by bpteague** [comment]
Hi @aliceberd,

The `PCAOp` operation uses scikit-learn's `sklearn.decomposition.PCA` object to perform the decomposition. After you call `estimate()`, it lives in the private attribute `_pca`. According to the scikit-learn documentation, you can get the proportion of variance explained by each component in the `explained_variance_ratio_` attribute. You'll need to compute the cumlative proportion yourself. I think (?) the components are ordered by the amount of variance they explain -- they usually are -- but I'm not 100% sure.

Two notes. First, this is *per event*, not computed on any statistics. And second, you will obviously need to be using the module interface, in a Jupyter notebook or similar -- this isn't something you can do with the point-and-click GUI.

Hope this helps. Closing.
