### ISSUE TITLE
Jupyter Notebooks Internal Server Error

### ISSUE THREAD

**Issue by jsoro89** [cytoflow/cytoflow#356]
### Thank you for your bug report!  

Please fill out the following template.

### DESCRIPTION:
  - What were you trying to do?
  - What happened?
  - What did you expect to happen?
  I have been trying to install cytoflow to use in Jupyter Notebooks either through the Anaconda Navigator or by launching it through Conda in the command line, but whenever I try, I get the message "500 : Internal Server Error" when I try to open any jupyter notebook. This does not happen outside of the cytoflow environment.
I tried the method of installing cytoflow in the anaconda navigator and using that environment to then launch jupyter notebooks, and I tried the method of adding the channel through the terminal.
I completely uninstalled Anaconda and Conda and reinstalled and tried everything again and had the same issue
**Don't forget to attach the log file to this bug report!** 

**If you are having trouble with a particular FCS file, please attach that file too.**

**Comment by bpteague** [comment]
Are you running this on an ARM-based Mac? (Ie, one with an M1, M2 or M3 chip?) I suspect that this is the problem. Unfortunately, I don't have access to an ARM-based Mac to test on. I am actively working to drop a new release in the next week or two that should have an experimental ARM build -- I'll try to remember to leave a note here when that happens, and if you could test it for me I'd appreciate it.

**Comment by jsoro89** [comment]
I am going to get an ARM-based Mac soon, so I will be able to test that for you. However, my current Mac is an Intel-based Mac. Any idea why that might be happening for me?

**Comment by jsoro89** [comment]
Hi,

I wanted to follow up on this. Any ideas on what might be causing me this issue?

**Comment by bpteague** [comment]
Hi @jsoro89 - without the ability to reproduce the issue, I can't directly solve it. However, I have updated all of the dependencies to modern releases and the build platforms to MacOS 13 (Intel) and 14 (ARM). 

If you want to help, try installing the Conda package from this page:
https://github.com/cytoflow/cytoflow/actions/runs/10570610176

(download the macos-conda-package artifact, unzip it, and then use the command-prompt conda command to install it.) Hopefully that will solve your issue.

PS - my "real" job is as a full-time professor at a small liberal arts college and our semester just started. The time I have to work on this moving forward is going to be limited, and a "reminder" like this isn't going to increase the likelihood that I can directly support you.

**Comment by bpteague** [comment]
I'm spinning a new release with up-to-date dependencies in the next few days. Try them, and re-open this issue if you're still having problems. All the caveats from the previous posts are still true, though.
