### ISSUE TITLE
Importing many flow files is very slow.

### ISSUE THREAD

**Issue by benweinberg89** [cytoflow/cytoflow#358]
### PLATFORM (Mac, PC, Linux, other):

Mac

### OPERATING SYSTEM (eg OSX 10.7, Windows 8.1):

Mac OS 10.15.1
M1 Pro

### SEVERITY (Critical? Major? Minor? Enhancement?):

I would deem this major as it severely impedes the utility of the app on large experiments

### DESCRIPTION:

Importing flow files into a single `Experiment` object progressively gets slower.

**Comment by benweinberg89** [comment]
I have found making these changes in `experiment.py` below can dramatically increase the speed of import:

Deleting this:
```
if( any(True for k in conditions if k not in self.conditions) or \
            any(True for k in self.conditions if k not in conditions) ):
            raise util.CytoflowError("Metadata for this tube should be {}"
                                     .format(list(self.conditions.keys())))
```

Changing this:
`meta_type = self.conditions[meta_name].dtype
`
To:
`meta_type = "category"
`

**Comment by benweinberg89** [comment]
Experiment A:
- 1,974,407 events across 42 samples
- 18 metadata categories

Without changes to experiment.py --> importing takes **115.83 seconds.**
With changes to experiment.py --> importing takes **12.49 seconds.**

Experiment B:
- 1,974,407 events across 42 samples
- 3 metadata categories

Without changes to experiment.py --> importing takes **6.84 seconds.**
With changes to experiment.py --> importing takes **3.45 seconds.**

**Comment by bpteague** [comment]
Fascinating. Thanks for the repro instructions and a pointer to where the slow code path is. I'll have a look.

**Comment by bpteague** [comment]
Profiling revealed that the Experiment.conditions property wasn't being cached. Caching it ( 6bf2ca00755d4c5cf35bb8130758e2c306254021 ) speeds these operations up 10-fold. Closing as fixed.
